### ISSUE TITLE
Adding webinars page to site

### ISSUE THREAD

**Issue by theo-cox** [life-itself/web3#105]
I've created a stub webinars page at https://github.com/life-itself/web3/tree/main/webinars but I'm told some coding is required to get it featured on the page.

## Acceptance

- [ ] /webinars page is live, featuring the text from webinars.md
- [ ] Page is displayed on the main menu

**Comment by rufuspollock** [comment]
@theo-cox the better option would be for this file to live at https://github.com/life-itself/web3/tree/main/site/content - i.e. no need for a subdirectory for now and you just have a `webinars.md` in the content directory. That will then show up - without anything needed from @khalilcodes In terms of the menu you can just edit https://github.com/life-itself/web3/blob/main/site/config/navLinks.js (hope structure is self-explanatory)
