### ISSUE TITLE
Rocket favicon

### ISSUE THREAD

**Issue by stevesong** [life-itself/web3#121]
Is the choice of a "rocket" as the favicon for the site intentional?  Some kind of ironic play on the "to the moon" crypto meme?  Perhaps something more neutral but indicative of the multidimensionality of the issue. e.g. https://thumbs.dreamstime.com/z/going-all-directions-4142189.jpg

**Comment by rufuspollock** [comment]
@stevesong good point and had this in #70 and just split out to #174 which could either merge to here or vice-versa.

To answer the question: rocket was accidental - just a placeholder.

Be great to have a solution.

**Comment by stevesong** [comment]
merge to #124

**Comment by rufuspollock** [comment]
FIXED. Duplicate of #124
