### ISSUE TITLE
Processing Stephen and Matthew Ranger Interview

### ISSUE THREAD

**Issue by theo-cox** [life-itself/web3#123]
Stephen has had a conversation with Matthew Ranger that should be processed and added to the site.

https://drive.google.com/file/d/19EnexwCcj-zasIzPltA_5qjBQsAnhmv5/view?usp=sharing

## Acceptance

- [x] Conversation on podcast platforms
- [x] Conversation on YouTube
- [x] Conversation on web3 site

**Comment by nathenf** [comment]
@theo-cox I have made an Issue workflow for this in Comms: https://github.com/life-itself/comms/issues/30 should we move it over here?

**Comment by theo-cox** [comment]
Sorry my bad for not using! If that's easier for you then please do
