### ISSUE TITLE
RHS table of contents

### ISSUE THREAD

**Issue by olayway** [life-itself/web3#152]
Priority over #153 

---

## User story
A user can quickly eyeball the contents of the current page by looking at the table of contents (ToC) on the right-hand side. He can also quickly navigate to different sections of the current page by clicking on a section title in the ToC and see where he's currently at thanks to highlighting of the currently focused section.

## Inspiration
Tailwind page:
![image](https://user-images.githubusercontent.com/52197250/167697665-b8cdead5-4fc3-4261-b805-b41fe1353d4d.png)

## Acceptance
- [x] ToC on the right-hand side that lists all the headings of the current page
- [x] subheadings of different levels should be accordingly indented
- [x] ToC should always be visible (doesn't hide on scrolling)
- [x] page should smooth-scroll to a given section upon clicking on its title in the ToC
- [x] title of the currently focused section should be highlighted

## References
Original issue: #93

**Comment by rufuspollock** [comment]
@olayway one issue with making the heading itself into a link is that you can't have links in the heading ... (i think this is the reason most people have a hover effect with actual link item outside of the text e.g. on the left as an icon). Examples of this behaviour on the news page https://web3.lifeitself.us/notes/news
