### ISSUE TITLE
Create a new 404 page

### ISSUE THREAD

**Issue by khalilcodes** [life-itself/web3#168]
The current 404 redirects to a blank white page that does not look as appealing and does not match the overall theme of the site.

# Acceptance

* [x] A better looking 404 page (with an icon/image?) that matches the site's theme. **DONE** *see /404 or /<any page that doesn't exist> or the screenshot below.*

## Screenshot

![Screen Shot 2022-06-12 at 10 54 06 PM](https://user-images.githubusercontent.com/42637597/173251486-a0abc412-8a46-4636-8f5f-0aab2de8c5a9.png)

**Comment by rufuspollock** [comment]
@khalilcodes nice and would have been good to do something like provide a link for people back to the front page.
