### ISSUE TITLE
Merging KlimaDAO pages

### ISSUE THREAD

**Issue by theo-cox** [life-itself/web3#211]
We have 2 KlimaDAO related pages: https://web3.lifeitself.org/claims/can-solve-collective-action-problem and https://web3.lifeitself.org/notes/klimadao.finance 

Along with our new analysis of the public goods problem which references Klima: https://web3.lifeitself.org/claims/can-solve-public-goods-problem

## Acceptance

- [ ] There is 1 single page for KlimaDAO analysis/deep dive
- [ ] Public goods problem page section on Klima references this page

**Comment by theo-cox** [comment]
FIXED. Collective action problems now links out to public goods, and KlimaDAO notes links out to the 2 deep dives

**Comment by rufuspollock** [comment]
@theo-cox what do you think of just deleting / removing https://web3.lifeitself.org/claims/can-solve-collective-action-problem - if we have a specific analysis on that now? (I think de-duplication is good!)

**Comment by theo-cox** [comment]
Sure @rufuspollock have deleted
