### ISSUE TITLE
Page layout for site

### ISSUE THREAD

**Issue by theo-cox** [life-itself/web3#212]
From Nathen (Comms Lead):

_One bit of feedback which should be a quick fix for the tech team. The spacing between contents and main content is a bit strange when we have so much space to the left. Would suggest shifting the main text more left to balance the spacing or making the contents box a different colour._

## Acceptance

- [ ] Decision made on what to do re spacing (e.g. shifting text, colour change)
- [ ] Decision implemented across the site

**Comment by khalilcodes** [comment]
@theo-cox @nathenf let me know if this looks right ..

<img width="1431" alt="Screen Shot 2022-12-15 at 5 17 14 PM" src="https://user-images.githubusercontent.com/42637597/207869247-8b42933c-4247-4884-a3c4-a35c3a10537f.png">

**Comment by nathenf** [comment]
@khalilcodes @theo-cox I would maybe say 5px more to the right. It looks better for sure

**Comment by rufuspollock** [comment]
@nathenf to note we had space on LHS for a full-site ToC. however we haven't done this for now.

@khalilcodes @nathenf i'd generally note we will probably upgrade web3 to flowershow at some point so i would be cautious to putting much time into this (if it is < 1h let's do it, otherwise i'd defer).

**Comment by khalilcodes** [comment]
@rufuspollock was quite a small change so had pushed that yesterday. @nathenf we can close this issue with the changes ported in.

**Comment by rufuspollock** [comment]
FIXED.
