### ISSUE TITLE
Dedicated claims page or claims section in guide

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#89]
@sdiehl i see we have a claims list now in the guide and we have  https://web3.lifeitself.us/claims

Question

* EITHER: shall we merge the guide stuff into the claims page https://web3.lifeitself.us/claims and just link that from the guide
* OR do you want to centralize the claims stuff in the guide (and we can remove claims page)?

Happy either way - just want to know how you would like to converge.

**Comment by sdiehl** [comment]
I think we should move all the claims/subclaims into a dedicated page. They're just temporarily cominging with the concepts at the moment, and given that there's a massive amount of pages on the wiki now I think moving claims to their own page make more sense.

**Comment by sdiehl** [comment]
The Wiki and Claims paes are now seperate as of [6636560](https://github.com/life-itself/web3/commit/663656026fa52a2ba24b3bf0f8bab1a7df9eb9e7).

**Comment by rufuspollock** [comment]
@sdiehl sounds good - note i'm using "wiki" to refer to pretty much everything (notes, guide, claims etc). By wiki do you mean `notes`?

BTW the info architecture diagram here may be useful https://github.com/life-itself/web3/blob/main/meta/design.md
