### ISSUE TITLE
Broken ideologies

### ISSUE THREAD

**Issue by sdiehl** [life-itself/web3#97]
Looks like the latest changes to the MDX router broke subdirectories within the `concepts` root directory. See for example:

https://web3.lifeitself.us/concepts/ideologies/market-fundamentalism

A quick hack would be to just move all the ideologies up a folder and then this should fix it. I'm happy to do this if need be.

**Comment by rufuspollock** [comment]
@khalilcodes can you have a quick look at this and see if there is an easy fix.

@sdiehl we can fix for now and my general sense is that we start flattening more and maybe using frontmatter in the markdown to differentiate different types of stuff (maybe we put most stuff in notes directory and just have types or categories). NB: this is a longer discussion and will open a separate issue for this.

**Comment by AceTheCreator** [comment]
@rufuspollock Can I work on this issue? If so any thing I need to understand?

**Comment by rufuspollock** [comment]
@AceTheCreator i think we are fixing this by removing the nested ideologies so nothing needed here. /cc @sdiehl

**Comment by khalilcodes** [comment]
Here's what I have so far on this for a better explanation on the issue.

* contentlayer not generating nested deep folders. for eg..

    ```
    content
        |____concepts                 // symlink from web3/concepts (outside site/)
            |____gold.md               // this works
            |____ideologies 
                |____capitalism.md  // this doesn't
    
        |___hello                           // create a test folder (no symlink)
            |____test
                |____hello.md          // this works
    
    ```

This looks more like a symlink issue.

**Comment by sdiehl** [comment]
I can just reverse my change and put all the `ideologies/*` up a folder. It doesn't matter to me either way really.

**Comment by rufuspollock** [comment]
@sdiehl did you fix this? I also wonder if we just merge ideologies into `notes/` and add a tag / type to them in frontmatter.
